# Generated by Django 5.1.2 on 2024-12-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huespedes',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='huespedes',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='huespedes',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='huespedes',
            name='id_huespedes',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='huespedes',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
