# Generated by Django 5.1.2 on 2024-12-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes_app', '0002_alter_huespedes_apellido_alter_huespedes_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huespedes',
            name='id',
        ),
        migrations.AlterField(
            model_name='huespedes',
            name='id_huespedes',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
