# Generated by Django 5.1.2 on 2024-12-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.IntegerField()),
                ('id_reserva', models.IntegerField()),
                ('fecha_de_pago', models.DateField()),
                ('metodo_de_pago', models.CharField(max_length=50)),
            ],
        ),
    ]
