# Generated by Django 5.1.2 on 2024-12-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
