# Generated by Django 5.1.2 on 2024-12-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitaciones',
            name='precio_por_noche',
            field=models.CharField(max_length=100),
        ),
    ]
