# Generated by Django 5.1.2 on 2024-12-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='Fecha_de_Entrada',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='Fecha_de_salida',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='id_habitacion',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='id_huespedes',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='id_reserva',
            field=models.CharField(max_length=10),
        ),
    ]
