# Generated by Django 5.1.2 on 2024-12-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0002_alter_reservas_fecha_de_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='id',
        ),
        migrations.AlterField(
            model_name='reservas',
            name='id_reserva',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
